/*global systemDictionary:true */
'use strict';

systemDictionary = {
    'Main': {
        'en': 'main site',
        'de': 'Hauptseite',
        'ru': 'главный сайт',
        'pt': 'site principal',
        'nl': 'hoofdsite',
        'fr': 'site principal',
        'it': 'sito principale',
        'es': 'sitio principal',
        'pl': 'strona główna',
        'zh-cn': '主要地点'
    },
    'Google': {
        'en': 'Google',
        'de': 'Google',
        'ru': 'Google',
        'pt': 'Google',
        'nl': 'Google',
        'fr': 'Google',
        'it': 'Google',
        'es': 'Google',
        'pl': 'Google',
        'zh-cn': '谷歌'
    },
    'Port:': {
        'en': 'Port:',
        'de': 'Port:',
        'ru': 'Порт:',
        'pt': 'Porta:',
        'nl': 'Haven:',
        'fr': 'Port:',
        'it': 'Porta:',
        'es': 'Puerto:',
        'pl': 'Port:',
        'zh-cn': '港口：'
    },
    'Activate Google account': {
        'en': 'Activate Google account',
        'de': 'Google-Konto aktivieren',
        'ru': 'Активировать аккаунт Google',
        'pt': 'Ativar conta do Google',
        'nl': 'Activeer Google-account',
        'fr': 'Activer le compte Google',
        'it': "Attiva l'account Google",
        'es': 'Activar cuenta de Google',
        'pl': 'Aktywuj konto Google',
        'zh-cn': '激活Google帐户'
    },
    'Client ID:': {
        'en': 'Client ID:',
        'de': 'Client ID:',
        'ru': 'ID клиента:',
        'pt': 'ID do Cliente:',
        'nl': 'Klant identificatie:',
        'fr': 'Identité du client:',
        'it': 'Identificativo cliente:',
        'es': 'Identificación del cliente:',
        'pl': 'Identyfikator klienta:',
        'zh-cn': '客户编号：'
    },
    'Client Secret:': {
        'en': 'Client Secret:',
        'de': 'Client Secret:',
        'ru': 'Секрет клиента:',
        'pt': 'Segredo do cliente:',
        'nl': 'Klantgeheim:',
        'fr': 'Secret client:',
        'it': 'Segreto cliente:',
        'es': 'Secreto del cliente:',
        'pl': 'Sekret klienta:',
        'zh-cn': '客户机密：'
    },
    'FQDN:': {
        'en': 'FQDN:',
        'de': 'FQDN:',
        'ru': 'Полное доменное имя:',
        'pt': 'FQDN:',
        'nl': 'FQDN:',
        'fr': 'FQDN:',
        'it': 'FQDN:',
        'es': 'FQDN:',
        'pl': 'FQDN:',
        'zh-cn': 'FQDN：'
    },
    'name': {
        'en': 'name',
        'de': 'Name',
        'ru': 'название',
        'pt': 'nome',
        'nl': 'naam',
        'fr': 'prénom',
        'it': 'nome',
        'es': 'nombre',
        'pl': 'imię',
        'zh-cn': '名称'
    },
    'id': {
        'en': 'id',
        'de': 'ID',
        'ru': 'мне бы',
        'pt': 'identidade',
        'nl': 'ID kaart',
        'fr': 'id',
        'it': 'id',
        'es': 'carné de identidad',
        'pl': 'ID',
        'zh-cn': 'ID'
    },
    'accessToken': {
        'en': 'access token',
        'de': 'Zugangstoken',
        'ru': 'токен доступа',
        'pt': 'token de acesso',
        'nl': 'toegangstoken',
        'fr': "jeton d'accès",
        'it': 'token di accesso',
        'es': 'token de acceso',
        'pl': 'token dostępu',
        'zh-cn': '访问令牌'
    },
    'refreshToken': {
        'en': 'refresh token',
        'de': 'Aktualisierungstoken',
        'ru': 'обновить токен',
        'pt': 'atualizar token',
        'nl': 'Token vernieuwen',
        'fr': 'rafraîchir le jeton',
        'it': 'token di aggiornamento',
        'es': 'token de actualización',
        'pl': 'odśwież token',
        'zh-cn': '刷新令牌'
    },
    'Nextcloud': {
        'en': 'Nextcloud',
        'de': 'Nextcloud',
        'ru': 'Nextcloud',
        'pt': 'Nextcloud',
        'nl': 'Nextcloud',
        'fr': 'Nextcloud',
        'it': 'Nextcloud',
        'es': 'Nextcloud',
        'pl': 'Nextcloud',
        'zh-cn': 'Nextcloud'
    },
    'Interval:': {
        'en': 'update interval (in hours)',
        'de': 'Aktualisierungsintervall (in Stunden)',
        'ru': 'интервал обновления (в часах)',
        'pt': 'intervalo de atualização (em horas)',
        'nl': 'update-interval (in uren)',
        'fr': 'intervalle de mise à jour (en heures)',
        'it': 'intervallo di aggiornamento (in ore)',
        'es': 'intervalo de actualización (en horas)',
        'pl': 'interwał aktualizacji (w godzinach)',
        'zh-cn': '更新间隔（以小时为单位）'
    },
    'country': {
        'en': 'country',
        'de': 'Land',
        'ru': 'страна',
        'pt': 'país',
        'nl': 'land',
        'fr': 'pays',
        'it': 'nazione',
        'es': 'país',
        'pl': 'kraj',
        'zh-cn': '国家'
    },
    'Activate Nextcloud account': {
        'en': 'Activate Nextcloud account',
        'de': 'Aktiviere den Nextcloud Account',
        'ru': 'Активировать учетную запись Nextcloud',
        'pt': 'Ativar conta Nextcloud',
        'nl': 'Activeer Nextcloud-account',
        'fr': 'Activer le compte Nextcloud',
        'it': "Attiva l'account Nextcloud",
        'es': 'Activa la cuenta de Nextcloud',
        'pl': 'Aktywuj konto Nextcloud',
        'zh-cn': '激活Nextcloud帐户'
    },
    'hostname': {
        'en': 'hostname',
        'de': 'Hostname',
        'ru': 'имя хоста',
        'pt': 'nome de anfitrião',
        'nl': 'hostname',
        'fr': "nom d'hôte",
        'it': 'Nome host',
        'es': 'nombre de host',
        'pl': 'nazwa hosta',
        'zh-cn': '主机名'
    },
    'username': {
        'en': 'username',
        'de': 'Nutzername',
        'ru': 'имя пользователя',
        'pt': 'nome do usuário',
        'nl': 'gebruikersnaam',
        'fr': "Nom d'utilisateur",
        'it': 'nome utente',
        'es': 'nombre de usuario',
        'pl': 'Nazwa Użytkownika',
        'zh-cn': '用户名'
    },
    'password': {
        'en': 'password',
        'de': 'Passwort',
        'ru': 'пароль',
        'pt': 'senha',
        'nl': 'wachtwoord',
        'fr': 'mot de passe',
        'it': "parola d'ordine",
        'es': 'contraseña',
        'pl': 'hasło',
        'zh-cn': '密码'
    }
};